modify orne_box_description
open-rdc/orne-box pull request #59
Opened 2022-03-18 04:52 UTC by IGC8810

orne_box_descriptionの編集を行いました。
主な変更点は、現在使用しているセンサのurdfの追加、ORNE-boxのurdfの変更です。

2022-03-18 14:47 UTC, NaokiTakahashi12 requested changes
内容確認しました．
特にxml周りのインデント乱れが見られるので，lintを使ってフォーマットを合わせると読みやすいと思います．
xmlであれば`xmllint`などがあります．

example
```
xmllint --format <file name> --output <file name>
```

2022-03-18 14:47 UTC, NaokiTakahashi12 commented on orne_box_description/urdf/links/base_link.urdf.xacro
> +		  </visual>
インデントの乱れ

2022-03-18 14:47 UTC, NaokiTakahashi12 commented on orne_box_description/urdf/joints/wheel_joint.urdf.xacro
> +	</xacro:macro>
インデントの乱れ

2022-03-18 14:47 UTC, NaokiTakahashi12 commented on orne_box_description/urdf/joints/caster_joint.urdf.xacro
> +	</xacro:macro>
インデントの乱れ

2022-03-18 14:47 UTC, NaokiTakahashi12 commented on orne_box_description/urdf/links/caster_link.urdf.xacro
> +</robot>
インデントの乱れ

2022-03-18 14:47 UTC, NaokiTakahashi12 commented on orne_box_description/urdf/links/wheel_link.urdf.xacro
> +	</xacro:macro>
インデントの乱れ

2022-03-18 14:47 UTC, NaokiTakahashi12 commented on orne_box_description/urdf/material_colors.xacro
> +		<color rgba="0.5 0.5 0.5 1.0"/>
インデントの乱れ

2022-03-18 14:47 UTC, NaokiTakahashi12 commented on orne_box_description/urdf/sensors/camera.urdf.xacro
> +    </link>
インデントの乱れ

2022-03-18 14:47 UTC, NaokiTakahashi12 commented on orne_box_description/package.xml
> +  <license>TODO</license>
設定をする．
不必要なコメントは消しても良い．

2022-03-19 18:55 UTC, IGC8810 commented on orne_box_description/package.xml
> +  <license>TODO</license>
不必要なコメントを削除しました．
maintainerについては今後の修正でまとめて設定します．

2022-03-19 18:56 UTC, merged